server:
  port: 8080

spring:
  application:
    name: health-record-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/health_record
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: https://<cluster-id>.<region>.aws.found.io:9243
    connection-timeout: 10s
    socket-timeout: 30s
    api-key: R2ltYTZaZ0JJbDNyZUV5WjFESXk6Rkw0aU9mekFFZGEyREdrb1dDREhwdw==

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minio123
  bucket-name: health-record

logging:
  level:
    com.Hootsybit: debug

wechat:
  appid: wxb3c0d315f90c2236
  secret: 4980c8ec8a26623468ba675ec0f99483